#!/bin/bash
#
# To enable this hook, rename this file to "pre-push".
# Remember to make it executable with: chmod +x

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
no_color='\033[0m'
reponame=$(git rev-parse --show-toplevel)

MODULES="$reponame/pkgs/*"
TEST_DIR="test"
TEST_RUN_SCRIPT="runtests.jl"


echo -e "\n${blue}Running pre-push hook\n${no_color}"
echo "Testing $reponame"

## Loop over all modules...
for module in $MODULES; do

    ## Run the tests for each module.
    ok=$(julia --project=@. "$module/$TEST_DIR/$TEST_RUN_SCRIPT")
    cmd_status=$?

    ## If bad status, error --leave with non-zero exit status (pre-push hook failed).
    if [[ $cmd_status -ne 0 ]]; then
        echo -e "\n${red}ERROR - Tests must pass before push!\n${no_color}"
        exit 1
    else
        echo -e "\n\n${blue} Tests passed!\n${no_color}"
        echo -e "${yellow} $ok"
    fi
done

echo -e "\n\n${green}Git hook was SUCCESSFUL!${no_color}\n"
