#!/bin/bash
#
# To enable this hook, rename this file to "pre-push".
# Remember to make it executable with: chmod +x

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
blue='\033[0;34m'
no_color='\033[0m'
reponame=$(git rev-parse --show-toplevel)


echo -e "\n${blue}Running pre-push hook\n${no_color}"
echo "Testing $reponame"

for module in $reponame/pkgs; do
    ok=$(julia --project=@. "$module/test/runtests.jl")

    if [[ $ok -ne 0 ]]; then
        echo -e "\n${red}ERROR - Tests must pass before push!\n${no_color}"
        exit 1
    else
        echo -e "\n${green} Tests passed!\n${no_color}"
    fi
done

echo -e "${green}Git hook was SUCCESSFUL!${no_color}\n"
