name = "Wquantiles"
uuid = "f2bb6186-f915-4bdd-96ba-5e4f8ac9549b"
authors = ["Scott McIntire <scottrsm@gmail.com>"]
version = "0.1.0"

[deps]
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"

[compat]
julia = "1.9"

