test:
  name: Julia ${{conf.version}} - ${{conf.os}} - ${{conf.arch}}
  runs-on: ${{conf.os}}
  strategy: 
    fail-fast: false
    conf:
      version:
        - 1.6
        - latest
      os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
      arch:
        - x64
  steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@latest
      with:
        version: ${{conf.version}}
        arch: ${{conf.arch}}
    - uses: julia-actions/julia-runtest@latest


