test:
  name: Julia ${{ matrix.version }} - ${{ conf.os }} - ${{ conf.arch }}
  runs-on: ${{ matrix.os }}
  strategy: 
    fail-fast: false
    matrix:
      version:
        - '1.6'
        - '1.9'
      os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
      arch:
        - x64
  steps:
    - uses: actions/checkout@v2
    - uses: julia-actions/setup-julia@latest
      with:
        version: ${{ matrix.version }}
        arch: ${{ matrix.arch }}
    - uses: julia-actions/julia-runtest@latest


